from .Paradiso   import ParadisoLoader
from .Boerderij  import BoerderijLoader
from .AFASLive   import AFASLiveLoader
from .Paard      import PaardLoader
from .ZiggoDome  import ZiggoDomeLoader
from .Tilburg013 import Tilburg013Loader
from .Melkweg    import MelkwegLoader
from .Arena      import ArenaLoader
from .LuxorLive  import LuxorLiveLoader
from .Gelredome  import GelredomeLoader
from .Steck      import SteckLoader
from .Carre      import CarreLoader